name: "\U0001F646‍♂️ Any issues"
description: Anything you talking.
title: "[ISSUE] "
body:
  - type: markdown
    attributes:
      value: |
        请先阅读 [README.md](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md) 和 [dependencies.md](https://github.com/lenML/ChatTTS-Forge/blob/master/docs/dependencies.md) 文件，并确保您的环境配置正确。
        在提交问题之前，请搜索现有的 issues 和 discussions 以避免重复。
        如果您的问题是关于使用公共服务，请先联系服务提供者。
  - type: checkboxes
    id: issue-check
    attributes:
      label: 确认清单
      description: 请确认以下所有选项：
      options:
        - label: 我已经阅读过 README.md 和 dependencies.md 文件
          required: true
        - label: 我已经确认之前没有 issue 或 discussion 涉及此 BUG
          required: true
        - label: 我已经确认问题发生在最新代码或稳定版本中
          required: true
        - label: 我已经确认问题与 API 无关
          required: true
        - label: 我已经确认问题与 WebUI 无关
          required: true
        - label: 我已经确认问题与 Finetune 无关
          required: true
  - type: textarea
    id: text
    attributes:
      label: 你的issues
      description: 请尽量附带上下文信息以及运行环境
    validations:
      required: true
