name: "\U0001F64B‍♀️ 新功能或建议 | Feature request"
description: 建议此项目增加的功能
title: "[Feature] "
labels: enhancement
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 确认清单
      description: 请确认以下所有选项：
      options:
        - label: 我已经仔细阅读[项目文档](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md)，确认现有功能无法解决我的需求
          required: true
        - label: 我已经检索过现有[issue](https://github.com/lenML/ChatTTS-Forge/issues)，确认与现有issue的内容并不重复
          required: true
        - label: 确认并非问题讨论而是 Feature request
          required: true
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？目前 ChatTTS Forge 的行为是什么？
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 可能的解决方案
      description: 您期望的解决方案，可能的实现方法或者可供参考的示例
    validations:
      required: false
